### ISSUE TITLE
Config loading

### ISSUE THREAD

**Issue by r3dsm0k3** [Kong/go-pdk#28]
Im trying to write a config schema which looks like this

```go
type Config struct {
  ApiEndPoint    string
  AuthModules    []Module
}


type Module struct {
  Name   string  
  Routes []string
}

```
and trying to load the configuration from a declarative config file.

```yaml
config: 
    apiendpoint: "http://localhost:5050/api/v1/permission/validate"
    authmodules: 
       - 
         name: application_mgmt
         routes: 
           - /api/v1/random
```

This configuration is resulting in an error

```sh
docker-compose up                                                                                                   ✔  17:19:32
Recreating plugin_kong-demo_1 ... done
Attaching to plugin_kong-demo_1
kong-demo_1  | 2020/03/23 16:19:35 [error] 1#0: init_by_lua error: /usr/local/share/lua/5.1/kong/init.lua:431: error parsing declarative config file /home/kong/config.yml:
kong-demo_1  | in 'services':
kong-demo_1  |   - in entry 1 of 'services':
kong-demo_1  |     in 'plugins':
kong-demo_1  |       - in entry 1 of 'plugins':
kong-demo_1  |         in 'config':
kong-demo_1  |           in 'authmodules': unknown field
```

I made sure the yaml is valid so there's no issue there. I'm able to parse the other fields though.
 
Can anyone help me explain what am I doing wrong here or if it is a bug in the go-pdk itself?

At this point I'm stuck and any help would be appreciated. Thanks
